version: '3.8'

services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/the/workdir/path
  cms:
    build:
      context: ./packages/backend
      dockerfile: ../Dockerfile.cms
    ports:
      - "1337:1337"
    volumes:
      - ./packages/backend:/the/workdir/path